[guides.getting-started]
title = "Getting Started"
series = true
description = """\
Take Qovery from zero to production in less than 10 minutes.\
"""

[guides.advanced]
title = "Advanced"
series = true
description = """\
Go beyond the basics, become a Qovery pro, and extract the full potential of Qovery.\
"""

[guides.tutorial]
title = "Tutorial"
series = false
description = """\
Simple step-by-step tutorials. \
"""

[guides.engineering]
title = "Engineering"
series = false
description = """\
We share our engineering learning with all of you. \
"""

#[guides.integrate]
#title = "Integrate"
#series = false
#description = """\
#Targeted guides for integrating platforms, data sources, and data destinations.\
#"""
